Initial commit

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,61 +3,61 @@ version: 2.1
 orbs: 
     slack: circleci/slack@4.10.1
 
-commands:
-  destroy_environment:
-    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
-    parameters:
-      Workflow_ID:
-        type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:5}
-    steps:
-      - run:
-          name: Destroy environment
-          when: on_fail
-          command: |
-            aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:5}
-            aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
-            aws cloudformation delete-stack --stack-name frontend-<< parameters.Workflow_ID >>
-  notify_on_failure:
-      steps:
-        - slack/notify:
-            event: fail
-            channel: $SLACK_DEFAULT_CHANNEL
-            template: basic_fail_1
-  notify_on_success:
-      steps:
-        - slack/notify:
-            event: pass
-            channel: $SLACK_DEFAULT_CHANNEL
-            template: success_tagged_deployment_1
+# commands:
+#   destroy_environment:
+#     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
+#     parameters:
+#       Workflow_ID:
+#         type: string
+#         default: ${CIRCLE_WORKFLOW_ID:0:5}
+#     steps:
+#       - run:
+#           name: Destroy environment
+#           when: on_fail
+#           command: |
+#             aws cloudformation delete-stack --stack-name backend-${CIRCLE_WORKFLOW_ID:0:5}
+#             aws s3 rm s3://udapeople-<<parameters.Workflow_ID>> --recursive
+#             aws cloudformation delete-stack --stack-name frontend-<< parameters.Workflow_ID >>
+#   notify_on_failure:
+#       steps:
+#         - slack/notify:
+#             event: fail
+#             channel: $SLACK_DEFAULT_CHANNEL
+#             template: basic_fail_1
+#   notify_on_success:
+#       steps:
+#         - slack/notify:
+#             event: pass
+#             channel: $SLACK_DEFAULT_CHANNEL
+#             template: success_tagged_deployment_1
 
 
-  revert-migrations:
-    description: Revert the last migration
-    parameters:
-      Workflow_ID:
-        type: string
-        default: ${CIRCLE_WORKFLOW_ID:0:7}
-    steps:
-      - run:
-          name: Revert migrations
-          when: on_fail
-          command: |
-            SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
-            echo "$SUCCESS"
-            # Logic for reverting the database state
-            if (( $SUCCESS == 1 ));
-            then
-              cd ~/project/backend
-              npm install
-              npm run migration:revert
-            fi
+#   revert-migrations:
+#     description: Revert the last migration
+#     parameters:
+#       Workflow_ID:
+#         type: string
+#         default: ${CIRCLE_WORKFLOW_ID:0:7}
+#     steps:
+#       - run:
+#           name: Revert migrations
+#           when: on_fail
+#           command: |
+#             SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/migration_<< parameters.Workflow_ID >>)
+#             echo "$SUCCESS"
+#             # Logic for reverting the database state
+#             if (( $SUCCESS == 1 ));
+#             then
+#               cd ~/project/backend
+#               npm install
+#               npm run migration:revert
+#             fi
             
 jobs:
 
   build-frontend:
     docker:
-      - image: circleci/node:13.8.0
+      - image: cimg/node:13.8.0
     # working_directory: ~/project/.circleci/ansible/inventory.txt
     steps:
       - checkout
@@ -90,160 +90,160 @@ jobs:
           paths: [backend/node_modules]
           key: backend-build
 
-  test-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: Test front-end
-          command: |
-            cd frontend
-            npm install
-            npm install oauth-sign
-            # npm run build
-            npm run test
+#   test-frontend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - restore_cache:
+#           keys: [frontend-build]
+#       - run:
+#           name: Test front-end
+#           command: |
+#             cd frontend
+#             npm install
+#             npm install oauth-sign
+#             # npm run build
+#             npm run test
                 
-  test-backend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Test Back-end
-          command: |
-            exit 0
-            cd backend
-            npm run test
+#   test-backend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - restore_cache:
+#           keys: [backend-build]
+#       - run:
+#           name: Test Back-end
+#           command: |
+#             exit 0
+#             cd backend
+#             npm run test
             
-  scan-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: Scan front-end
-          command: |
-            exit 0
-            npm audit
-  scan-backend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Scan Back-end
-          command: |
-            exit 0
-            npm audit
-  deploy-infrastructure:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            yum install -y tar gzip
-      # - run:
-      #     name: Ensure back-end infrastructure exists
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/backend.yml \
-      #         --tags project=udapeople \
-      #         --stack-name "backend" \
-      #         --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:5}
+#   scan-frontend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - restore_cache:
+#           keys: [frontend-build]
+#       - run:
+#           name: Scan front-end
+#           command: |
+#             exit 0
+#             npm audit
+#   scan-backend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - restore_cache:
+#           keys: [backend-build]
+#       - run:
+#           name: Scan Back-end
+#           command: |
+#             exit 0
+#             npm audit
+#   deploy-infrastructure:
+#     docker:
+#       - image: amazon/aws-cli
+#     steps:
+#       - checkout
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             yum install -y tar gzip
+#       # - run:
+#       #     name: Ensure back-end infrastructure exists
+#       #     command: |
+#       #       aws cloudformation deploy \
+#       #         --template-file .circleci/files/backend.yml \
+#       #         --tags project=udapeople \
+#       #         --stack-name "backend" \
+#       #         --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:5}
 
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              --tags project=udapeople \
-              --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:5}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:5}"
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
-            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
+#       - run:
+#           name: Ensure front-end infrastructure exist
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file .circleci/files/frontend.yml \
+#               --tags project=udapeople \
+#               --stack-name "frontend-${CIRCLE_WORKFLOW_ID:0:5}" \
+#               --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:5}"
+#       - run:
+#           name: Add back-end ip to ansible inventory
+#           command: |
+#             aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> .circleci/ansible/inventory.txt
+#       - persist_to_workspace:
+#           root: ~/
+#           paths:
+#             - project/.circleci/ansible/inventory.txt
+# #       # Here's where you will add some code to rollback on failure      
+#       # - destroy_environment
+#   configure-infrastructure:
+#     docker:
+#       - image: mareimorsy/aws-node
+#     steps:
+#       - checkout
+#       - add_ssh_keys:
+#           fingerprints: ["0d:a0:d2:30:e7:40:31:70:0e:69:45:04:ad:36:0b:8c"]
+#       # - run:
+#       #     name: "Install Dependencies"
+#       #     command: |
+#       #       apk add ansible gzip openssh-client
+#       # - attach_workspace:
+#       #     at: ~/
+#       - run:
+#           name: Configure server
+#           command: |
+#             ls
+#             pwd
+#             cd .circleci/ansible
+#             aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory.txt
+#             cat inventory.txt
+#             # ansible-playbook -i inventory.txt configure-server.yml -vv
+#             ansible-playbook -i inventory.txt prometheus-exporter.yml -vv
 #       # Here's where you will add some code to rollback on failure      
-      # - destroy_environment
-  configure-infrastructure:
-    docker:
-      - image: mareimorsy/aws-node
-    steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints: ["0d:a0:d2:30:e7:40:31:70:0e:69:45:04:ad:36:0b:8c"]
-      # - run:
-      #     name: "Install Dependencies"
-      #     command: |
-      #       apk add ansible gzip openssh-client
-      # - attach_workspace:
-      #     at: ~/
-      - run:
-          name: Configure server
-          command: |
-            ls
-            pwd
-            cd .circleci/ansible
-            aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text >> inventory.txt
-            cat inventory.txt
-            # ansible-playbook -i inventory.txt configure-server.yml -vv
-            ansible-playbook -i inventory.txt prometheus-exporter.yml -vv
-      # Here's where you will add some code to rollback on failure      
 
-  run-migrations:
-    docker: 
-      - image: mareimorsy/aws-node
+#   run-migrations:
+#     docker: 
+#       - image: mareimorsy/aws-node
 
-    steps:
-      - checkout
-      - run:
-          name: Run migrations
-          command: |
-            export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            cd backend
-            npm install
-            npm run premigrations
-            npm run migrations
-      # - run:
-      #     name: Send migration results to memstash
-      #     command: |
-      #       # Your code here
-      #       exit 1
-     # Here's where you will add some code to rollback on failure      
+#     steps:
+#       - checkout
+#       - run:
+#           name: Run migrations
+#           command: |
+#             export TYPEORM_HOST=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+#             cd backend
+#             npm install
+#             npm run premigrations
+#             npm run migrations
+#       # - run:
+#       #     name: Send migration results to memstash
+#       #     command: |
+#       #       # Your code here
+#       #       exit 1
+#      # Here's where you will add some code to rollback on failure      
 
-  deploy-frontend:
-    docker:
-      - image: mareimorsy/aws-node
-    steps:
-      - checkout
-      - run:
-          name: Deploy Frontend
-          command: |
-            export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-             echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" 
-            # Build the frontend
-            cd frontend
-            echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" > .env
-            npm install
-            npm run build:prod
-            # aws s3 sync dist s3://udapeople-project
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:5} --recursive
-#       # Here's where you will add some code to rollback on failure      
+#   deploy-frontend:
+#     docker:
+#       - image: mareimorsy/aws-node
+#     steps:
+#       - checkout
+#       - run:
+#           name: Deploy Frontend
+#           command: |
+#             export BACKEND_PUBLIC_IP=$(aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+#              echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" 
+#             # Build the frontend
+#             cd frontend
+#             echo "API_URL=http://$BACKEND_PUBLIC_IP:3030" > .env
+#             npm install
+#             npm run build:prod
+#             # aws s3 sync dist s3://udapeople-project
+#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:5} --recursive
+# #       # Here's where you will add some code to rollback on failure      
                     
   deploy-backend:
     docker:
@@ -342,8 +342,8 @@ jobs:
 workflows:
   default:
     jobs:
-      # - build-frontend
-      # - build-backend
+        - build-frontend
+        - build-backend
       # - test-frontend:
       #     requires: [build-frontend]
       # - test-backend:
